var equipments = [
  "body_weight",
  "dumbbell",
  "band",
  "barbell",
  "kettlebell",
  "ball",
  "treadmill",
  "elliptical",
];

var level = ["beginner", "intermediate", "advance"];

var workout = {
  beginner: {
    body_weight: [
      { name: "Push-ups", met_value: 3.8 },
      { name: "Bodyweight squats", met_value: 3.0 },
      { name: "Plank", met_value: 2.5 },
      { name: "Jumping jacks", met_value: 7.0 },
      { name: "Wall sits", met_value: 2.0 },
      { name: "Glute bridges", met_value: 2.5 },
      { name: "Leg raises", met_value: 3.0 },
      { name: "Bicycle crunches", met_value: 4.0 },
      { name: "Standing calf raises", met_value: 2.5 },
      { name: "Arm circles", met_value: 2.0 },
      { name: "High knees", met_value: 8.0 },
      { name: "Tricep dips using a chair", met_value: 3.0 },
      { name: "Standing toe touches", met_value: 3.5 },
      { name: "Bird-dogs", met_value: 3.0 },
      { name: "Standing leg lifts", met_value: 3.0 },
      { name: "Wall push-ups", met_value: 3.0 },
      { name: "Modified burpees", met_value: 6.0 },
      { name: "Chair squats", met_value: 3.5 },
      { name: "Knee push-ups", met_value: 3.0 },
      { name: "Side leg lifts", met_value: 3.0 },
      { name: "Seated leg extensions", met_value: 2.0 },
      { name: "Seated leg curls", met_value: 2.0 },
      { name: "Step-ups on a sturdy chair", met_value: 4.0 },
      { name: "Wrist curls", met_value: 2.0 },
      { name: "Side leg raises", met_value: 3.0 },
      { name: "Leg circles", met_value: 2.5 },
      { name: "Arm punches", met_value: 4.0 },
      { name: "Arm curls with water bottles", met_value: 3.0 },
      { name: "Front kicks", met_value: 4.5 },
      { name: "Lateral arm raises", met_value: 2.5 },
      { name: "Shoulder shrugs", met_value: 2.5 },
      { name: "Seated leg lifts", met_value: 2.0 },
      { name: "Clamshells", met_value: 2.5 },
      { name: "Wrist flexor and extensor stretches", met_value: 1.5 },
      { name: "Plank leg lifts", met_value: 3.0 },
      { name: "Standing side crunches", met_value: 3.0 },
      { name: "Arm swings", met_value: 3.0 },
      { name: "Butt kicks", met_value: 6.0 },
      { name: "Wall angels", met_value: 2.0 },
      { name: "Seated marches", met_value: 2.5 },
      { name: "Leg swings", met_value: 3.0 },
      { name: "Standing torso twists", met_value: 2.5 },
      { name: "Seated knee extensions", met_value: 2.0 },
      { name: "Shoulder circles", met_value: 2.0 },
      { name: "Standing calf raises", met_value: 3.0 },
      { name: "Seated marches", met_value: 2.5 },
      { name: "Arm crosses", met_value: 2.0 },
      { name: "Wall marches", met_value: 2.5 },
      { name: "Seated torso twists", met_value: 2.0 },
    ],
    dumbbell: [
      { name: "Dumbbell Squats", met_value: 4.5 },
      { name: "Dumbbell Lunges", met_value: 4.0 },
      { name: "Dumbbell Deadlifts", met_value: 4.0 },
      { name: "Dumbbell Rows", met_value: 3.5 },
      { name: "Dumbbell Bench Press", met_value: 3.5 },
      { name: "Dumbbell Bicep Curls", met_value: 3.0 },
      { name: "Dumbbell Tricep Extensions", met_value: 3.0 },
      { name: "Dumbbell Shoulder Press", met_value: 3.5 },
      { name: "Dumbbell Lateral Raises", met_value: 3.0 },
      { name: "Dumbbell Front Raises", met_value: 3.0 },
      { name: "Dumbbell Shrugs", met_value: 3.0 },
      { name: "Dumbbell Step-ups", met_value: 4.0 },
      { name: "Dumbbell Russian Twists", met_value: 3.5 },
      { name: "Dumbbell Woodchops", met_value: 3.5 },
      { name: "Dumbbell Hammer Curls", met_value: 3.0 },
      { name: "Dumbbell Wrist Curls", met_value: 2.5 },
      { name: "Dumbbell Side Raises", met_value: 3.0 },
      { name: "Dumbbell Bent-Over Rows", met_value: 3.5 },
      { name: "Dumbbell Plank Rows", met_value: 3.0 },
      { name: "Dumbbell Leg Raises", met_value: 2.5 },
      { name: "Dumbbell Sit-ups", met_value: 3.0 },
      { name: "Dumbbell Standing Calf Raises", met_value: 2.5 },
      { name: "Dumbbell Reverse Flyes", met_value: 3.0 },
      { name: "Dumbbell Skull Crushers", met_value: 3.0 },
      { name: "Dumbbell Farmers Walk", met_value: 4.0 },
    ],
    band: [
      { name: "Resistance Band Squats", met_value: 4.0 },
      { name: "Resistance Band Deadlifts", met_value: 4.0 },
      { name: "Resistance Band Rows", met_value: 3.5 },
      { name: "Resistance Band Bicep Curls", met_value: 3.0 },
      { name: "Resistance Band Tricep Extensions", met_value: 3.0 },
      { name: "Resistance Band Pull-aparts", met_value: 3.0 },
      { name: "Resistance Band Lat Pulldowns", met_value: 3.5 },
      { name: "Resistance Band Chest Press", met_value: 3.0 },
      { name: "Resistance Band Leg Press", met_value: 4.0 },
      { name: "Resistance Band Hip Abductions", met_value: 3.0 },
      { name: "Resistance Band Glute Bridges", met_value: 3.0 },
      { name: "Resistance Band Lateral Leg Raises", met_value: 3.0 },
      { name: "Resistance Band Shoulder Press", met_value: 3.5 },
      { name: "Resistance Band Upright Rows", met_value: 3.0 },
      { name: "Resistance Band Face Pulls", met_value: 3.0 },
      { name: "Resistance Band Bicycle Crunches", met_value: 4.0 },
      { name: "Resistance Band Plank", met_value: 3.0 },
      { name: "Resistance Band Side Steps", met_value: 3.0 },
      { name: "Resistance Band Good Mornings", met_value: 3.5 },
      { name: "Resistance Band Wall Sits", met_value: 3.0 },
      { name: "Resistance Band Seated Leg Extensions", met_value: 3.0 },
      { name: "Resistance Band Kneeling Crunches", met_value: 3.0 },
      { name: "Resistance Band Arm Circles", met_value: 2.5 },
      {
        name: "Resistance Band Wrist Flexor and Extensor Exercises",
        met_value: 2.0,
      },
      { name: "Resistance Band Pallof Presses", met_value: 3.5 },
    ],
    barbell: [
      { name: "Barbell Squats", met_value: 6.0 },
      { name: "Barbell Deadlifts", met_value: 6.0 },
      { name: "Barbell Rows", met_value: 4.5 },
      { name: "Barbell Bench Press", met_value: 4.5 },
      { name: "Barbell Lunges", met_value: 4.0 },
      { name: "Barbell Bicep Curls", met_value: 3.0 },
      { name: "Barbell Tricep Extensions", met_value: 3.0 },
      { name: "Barbell Shoulder Press", met_value: 4.0 },
      { name: "Barbell Shrugs", met_value: 4.0 },
      { name: "Barbell Romanian Deadlifts", met_value: 4.5 },
      { name: "Barbell Bent-Over Rows", met_value: 4.0 },
      { name: "Barbell Upright Rows", met_value: 4.0 },
      { name: "Barbell Front Squats", met_value: 4.5 },
      { name: "Barbell Hip Thrusts", met_value: 4.0 },
      { name: "Barbell Calf Raises", met_value: 3.0 },
      { name: "Barbell Skull Crushers", met_value: 3.0 },
      { name: "Barbell Leg Press", met_value: 5.0 },
      { name: "Barbell Good Mornings", met_value: 3.5 },
      { name: "Barbell Glute Bridges", met_value: 4.0 },
      { name: "Barbell Plank Rows", met_value: 3.5 },
      { name: "Barbell Russian Twists", met_value: 4.0 },
      { name: "Barbell Farmers Walk", met_value: 4.5 },
      { name: "Barbell Wrist Curls", met_value: 2.5 },
      { name: "Barbell Drag Curls", met_value: 3.0 },
      { name: "Barbell Seated Press", met_value: 4.0 },
    ],
    kettlebell: [
      { name: "Kettlebell Swings", met_value: 6.0 },
      { name: "Kettlebell Goblet Squats", met_value: 4.5 },
      { name: "Kettlebell Lunges", met_value: 4.0 },
      { name: "Kettlebell Turkish Get-ups", met_value: 5.0 },
      { name: "Kettlebell Russian Twists", met_value: 4.0 },
      { name: "Kettlebell Deadlifts", met_value: 4.5 },
      { name: "Kettlebell Rows", met_value: 3.5 },
      { name: "Kettlebell Halo", met_value: 3.5 },
      { name: "Kettlebell Figure 8s", met_value: 3.5 },
      { name: "Kettlebell Cleans", met_value: 4.5 },
      { name: "Kettlebell Snatches", met_value: 5.0 },
      { name: "Kettlebell High Pulls", met_value: 4.5 },
      { name: "Kettlebell Sumo Deadlift High Pulls", met_value: 4.5 },
      { name: "Kettlebell Windmills", met_value: 3.5 },
      { name: "Kettlebell Farmer's Walk", met_value: 4.0 },
      { name: "Kettlebell Russian Press", met_value: 3.5 },
      { name: "Kettlebell Lateral Swings", met_value: 4.0 },
      { name: "Kettlebell Plank Pull-throughs", met_value: 3.5 },
      { name: "Kettlebell Bent-over Rows", met_value: 4.0 },
      { name: "Kettlebell Turkish Sit-ups", met_value: 4.0 },
      { name: "Kettlebell Side Bends", met_value: 3.5 },
      { name: "Kettlebell Goblet Lunges", met_value: 4.0 },
      { name: "Kettlebell Romanian Deadlifts", met_value: 4.0 },
      { name: "Kettlebell Split Squats", met_value: 4.0 },
      { name: "Kettlebell Cleans and Presses", met_value: 4.5 },
    ],
    ball: [
      { name: "Stability Ball Squats", met_value: 3.0 },
      { name: "Stability Ball Wall Sits", met_value: 2.5 },
      { name: "Stability Ball Lunges", met_value: 3.0 },
      { name: "Stability Ball Push-ups", met_value: 3.5 },
      { name: "Stability Ball Planks", met_value: 3.0 },
      { name: "Stability Ball Russian Twists", met_value: 3.5 },
      { name: "Stability Ball Glute Bridges", met_value: 3.0 },
      { name: "Stability Ball Leg Curls", met_value: 2.5 },
      { name: "Stability Ball Rollouts", met_value: 3.0 },
      { name: "Stability Ball Seated Crunches", met_value: 3.0 },
      { name: "Stability Ball Superman", met_value: 2.5 },
      { name: "Stability Ball Tricep Dips", met_value: 3.0 },
      { name: "Stability Ball Back Extensions", met_value: 2.5 },
      { name: "Stability Ball Hamstring Curls", met_value: 3.0 },
      { name: "Stability Ball Wall Angels", met_value: 2.5 },
      { name: "Stability Ball Pike", met_value: 3.0 },
      { name: "Stability Ball Hip Raises", met_value: 3.0 },
      { name: "Stability Ball Mountain Climbers", met_value: 4.0 },
      { name: "Stability Ball Reverse Crunches", met_value: 3.0 },
      { name: "Stability Ball Jackknives", met_value: 3.0 },
      { name: "Stability Ball Bicep Curls", met_value: 2.5 },
      { name: "Stability Ball Front Raises", met_value: 2.5 },
      { name: "Stability Ball Side Leg Raises", met_value: 3.0 },
      { name: "Stability Ball Chest Press", met_value: 2.5 },
      { name: "Stability Ball Lat Pulldowns", met_value: 3.0 },
    ],
    treadmill: [
      { name: "Walking at a Moderate Pace", met_value: 3.9 },
      { name: "Slow Jogging", met_value: 5.0 },
      { name: "Incline Walking", met_value: 4.5 },
      { name: "Treadmill Hill Climbs", met_value: 6.0 },
      { name: "Brisk Walking", met_value: 3.9 },
      { name: "Interval Walking and Jogging", met_value: 6.0 },
      { name: "Side Shuffles", met_value: 5.5 },
      { name: "Backward Walking", met_value: 5.0 },
      { name: "Treadmill Lunges", met_value: 5.0 },
      { name: "Treadmill Push-ups", met_value: 5.0 },
      { name: "Treadmill High Knees", met_value: 7.0 },
      { name: "Treadmill Planks", met_value: 3.9 },
      { name: "Treadmill Mountain Climbers", met_value: 8.0 },
      { name: "Treadmill Side Steps", met_value: 6.0 },
      { name: "Treadmill Sprints (with caution)", met_value: 8.0 },
      { name: "Treadmill Butt Kicks", met_value: 6.5 },
      { name: "Treadmill Leg Swings", met_value: 4.5 },
      { name: "Treadmill Cross-Training", met_value: 6.0 },
      { name: "Treadmill Calf Raises", met_value: 4.5 },
      { name: "Treadmill Stepper Climbs", met_value: 6.0 },
      { name: "Treadmill Walking Lunges", met_value: 5.0 },
      { name: "Treadmill Arm Swings", met_value: 4.0 },
      { name: "Treadmill Side Leg Lifts", met_value: 4.0 },
      { name: "Treadmill Reverse Lunges", met_value: 5.5 },
      { name: "Treadmill Walking Deadlifts", met_value: 4.5 },
    ],
    elliptical: [
      { name: "Elliptical Machine Forward Pedaling", met_value: 5.0 },
      { name: "Elliptical Machine Reverse Pedaling", met_value: 5.0 },
      { name: "Elliptical Machine Interval Training", met_value: 6.0 },
      { name: "Elliptical Machine Cross Trainer", met_value: 6.5 },
      { name: "Elliptical Machine High Resistance", met_value: 6.5 },
      { name: "Elliptical Machine Arm Focus", met_value: 6.0 },
      { name: "Elliptical Machine Leg Focus", met_value: 6.0 },
      { name: "Elliptical Machine Cardio Workout", met_value: 6.0 },
      { name: "Elliptical Machine Uphill Climbing", met_value: 6.5 },
      { name: "Elliptical Machine Hill Intervals", met_value: 7.0 },
      { name: "Elliptical Machine Cross Country Mode", met_value: 7.0 },
      { name: "Elliptical Machine Glute Blaster", met_value: 6.0 },
      { name: "Elliptical Machine Core Engage", met_value: 6.0 },
      { name: "Elliptical Machine HIIT Workout", met_value: 7.0 },
      { name: "Elliptical Machine Total Body Workout", met_value: 6.5 },
      { name: "Elliptical Machine Steady State Cardio", met_value: 6.0 },
      {
        name: "Elliptical Machine Forward and Backward Motion",
        met_value: 6.5,
      },
      { name: "Elliptical Machine Lateral Steps", met_value: 6.5 },
      { name: "Elliptical Machine Arm Circles", met_value: 6.0 },
      { name: "Elliptical Machine Leg Circles", met_value: 6.0 },
      { name: "Elliptical Machine Side-to-Side Motion", met_value: 6.5 },
      { name: "Elliptical Machine High Knee March", met_value: 7.0 },
      { name: "Elliptical Machine Butt Kicks", met_value: 7.5 },
      { name: "Elliptical Machine Single-Leg Pedaling", met_value: 6.5 },
      { name: "Elliptical Machine Single-Arm Pedaling", met_value: 6.0 },
    ],
  },
  intermediate: {
    body_weight: [
      { name: "Burpees", met_value: 8.0 },
      { name: "Mountain climbers", met_value: 8.0 },
      { name: "Lunges", met_value: 5.0 },
      { name: "Russian twists", met_value: 5.0 },
      { name: "Diamond push-ups", met_value: 5.0 },
      { name: "Superman", met_value: 3.0 },
      { name: "Plank with leg lifts", met_value: 4.0 },
      { name: "Bicycle crunches", met_value: 4.0 },
      { name: "Jump squats", met_value: 8.0 },
      { name: "Tricep push-ups", met_value: 5.0 },
      { name: "Side plank", met_value: 3.5 },
      { name: "Dumbbell curls", met_value: 3.5 },
      { name: "Dumbbell squats", met_value: 5.0 },
      { name: "Box jumps (using a sturdy step or box)", met_value: 8.0 },
      { name: "High plank with shoulder taps", met_value: 4.0 },
      { name: "Skater jumps", met_value: 6.0 },
      { name: "Spiderman push-ups", met_value: 5.5 },
      { name: "Pike push-ups", met_value: 6.0 },
      { name: "Reverse lunges", met_value: 5.0 },
      { name: "Lateral leg raises", met_value: 3.5 },
      { name: "Plank with knee to elbow", met_value: 4.5 },
      { name: "Jumping lunges", met_value: 8.0 },
      { name: "Push-up to side plank", met_value: 6.0 },
      { name: "Dumbbell rows", met_value: 4.0 },
      { name: "Russian twists with a weight", met_value: 5.0 },
      { name: "Bicycle crunches with a twist", met_value: 5.0 },
      { name: "Sumo squats", met_value: 5.0 },
      { name: "Standing dumbbell shoulder press", met_value: 4.0 },
      { name: "Dumbbell lunges", met_value: 5.0 },
      { name: "Plank with hip dips", met_value: 4.5 },
      { name: "Dumbbell deadlifts", met_value: 5.0 },
      { name: "Jumping jacks with dumbbells", met_value: 7.0 },
      { name: "Tricep kickbacks", met_value: 4.0 },
      { name: "Bulgarian split squats", met_value: 5.0 },
      { name: "Standing calf raises with dumbbells", met_value: 3.5 },
      { name: "Leg press with resistance bands", met_value: 6.0 },
      { name: "Side plank with leg lift", met_value: 4.0 },
      { name: "Dumbbell step-ups", met_value: 5.0 },
      { name: "Bent-over rows", met_value: 4.0 },
      { name: "Dumbbell lateral raises", met_value: 4.0 },
      { name: "Push-up to T-raise", met_value: 6.0 },
      { name: "Bicycle crunches with a twist and dumbbell", met_value: 5.0 },
      { name: "Dumbbell front raises", met_value: 4.0 },
      { name: "Plank with alternating leg lifts", met_value: 4.5 },
      { name: "Dumbbell woodchops", met_value: 4.5 },
      { name: "Standing oblique crunches with a dumbbell", met_value: 4.0 },
      { name: "Dumbbell chest press", met_value: 4.0 },
      { name: "Reverse flyes with dumbbells", met_value: 4.0 },
      { name: "Dumbbell Russian twists", met_value: 4.5 },
      { name: "Dumbbell burpees", met_value: 8.0 },
    ],
    dumbbell: [
      { name: "Dumbbell Lunges with Overhead Press", met_value: 6.0 },
      { name: "Dumbbell Bulgarian Split Squats", met_value: 5.5 },
      { name: "Dumbbell Renegade Rows", met_value: 5.0 },
      { name: "Dumbbell Incline Bench Press", met_value: 5.0 },
      { name: "Dumbbell Romanian Deadlifts", met_value: 5.5 },
      { name: "Dumbbell Push Press", met_value: 5.0 },
      { name: "Dumbbell Arnold Press", met_value: 5.0 },
      { name: "Dumbbell Front Squats", met_value: 5.5 },
      { name: "Dumbbell Bent-Over Rows", met_value: 5.0 },
      { name: "Dumbbell Box Jumps", met_value: 7.0 },
      { name: "Dumbbell Russian Twists with Weight", met_value: 5.5 },
      { name: "Dumbbell Plank Rows", met_value: 5.0 },
      { name: "Dumbbell Turkish Get-ups", met_value: 6.5 },
      { name: "Dumbbell Lateral Lunges", met_value: 6.0 },
      { name: "Dumbbell Skull Crushers", met_value: 4.5 },
      { name: "Dumbbell Incline Curls", met_value: 4.5 },
      { name: "Dumbbell Step-ups with Knee Raise", met_value: 6.0 },
      { name: "Dumbbell Sit-up and Press", met_value: 5.0 },
      { name: "Dumbbell Suitcase Deadlifts", met_value: 5.5 },
      { name: "Dumbbell Walking Lunges", met_value: 6.0 },
      { name: "Dumbbell Tricep Kickbacks", met_value: 4.5 },
      { name: "Dumbbell Plank with Alternating Rows", met_value: 5.5 },
      { name: "Dumbbell Twisting Lunges", met_value: 6.0 },
      { name: "Dumbbell Side Planks with Lateral Raise", met_value: 5.0 },
      { name: "Dumbbell Bulgarian Split Jumps", met_value: 7.5 },
    ],
    band: [
      { name: "Resistance Band Squats with Overhead Press", met_value: 5.0 },
      { name: "Resistance Band Deadlifts", met_value: 4.5 },
      { name: "Resistance Band Rows with Band Pull-aparts", met_value: 4.0 },
      {
        name: "Resistance Band Bicep Curls with Tricep Extensions",
        met_value: 4.0,
      },
      {
        name: "Resistance Band Lat Pulldowns with Chest Press",
        met_value: 4.0,
      },
      { name: "Resistance Band Leg Press with Hip Abductions", met_value: 4.5 },
      {
        name: "Resistance Band Glute Bridges with Lateral Leg Raises",
        met_value: 4.0,
      },
      {
        name: "Resistance Band Shoulder Press with Upright Rows",
        met_value: 4.5,
      },
      {
        name: "Resistance Band Face Pulls with Bicycle Crunches",
        met_value: 5.0,
      },
      { name: "Resistance Band Plank with Side Steps", met_value: 4.5 },
      { name: "Resistance Band Good Mornings with Wall Sits", met_value: 5.0 },
      {
        name: "Resistance Band Seated Leg Extensions with Kneeling Crunches",
        met_value: 4.5,
      },
      {
        name: "Resistance Band Arm Circles with Wrist Exercises",
        met_value: 3.5,
      },
      {
        name: "Resistance Band Pallof Presses with Glute Kickbacks",
        met_value: 4.5,
      },
      { name: "Resistance Band Lunge and Twist", met_value: 5.0 },
      { name: "Resistance Band Push-ups with Leg Raises", met_value: 4.5 },
      { name: "Resistance Band Squat Jumps with Plank Rows", met_value: 6.0 },
      {
        name: "Resistance Band Mountain Climbers with Reverse Flyes",
        met_value: 5.0,
      },
      {
        name: "Resistance Band High Knees with Russian Twists",
        met_value: 6.5,
      },
      { name: "Resistance Band Burpees", met_value: 7.0 },
      { name: "Resistance Band Box Steps with Curl and Press", met_value: 5.5 },
      {
        name: "Resistance Band Wall Sits with Lateral Leg Raises",
        met_value: 5.0,
      },
      {
        name: "Resistance Band Plank Rotations with Squat Pulses",
        met_value: 6.0,
      },
      { name: "Resistance Band Bear Crawls", met_value: 7.5 },
    ],
    barbell: [
      { name: "Barbell Squats with Overhead Press", met_value: 6.5 },
      { name: "Barbell Deadlifts with Bent-Over Rows", met_value: 6.0 },
      { name: "Barbell Bench Press with Leg Raises", met_value: 6.0 },
      { name: "Barbell Lunges with Bicep Curls", met_value: 6.0 },
      { name: "Barbell Rows with Tricep Extensions", met_value: 5.5 },
      { name: "Barbell Front Squats with Upright Rows", met_value: 6.0 },
      { name: "Barbell Romanian Deadlifts with Shrugs", met_value: 6.0 },
      { name: "Barbell Push Press with Skull Crushers", met_value: 5.5 },
      { name: "Barbell Sumo Deadlift High Pulls", met_value: 6.5 },
      { name: "Barbell Bent-Over Rows with Plank Rows", met_value: 5.5 },
      { name: "Barbell Box Jumps with Russian Twists", met_value: 7.0 },
      { name: "Barbell Lateral Lunges with Side Leg Raises", met_value: 6.0 },
      { name: "Barbell Good Mornings with Wall Sits", met_value: 6.0 },
      { name: "Barbell Glute Bridges with Leg Raises", met_value: 5.5 },
      {
        name: "Barbell Bulgarian Split Jumps with Calf Raises",
        met_value: 7.5,
      },
      { name: "Barbell Push-ups with Renegade Rows", met_value: 6.0 },
      { name: "Barbell Thrusters with Plank Rotations", met_value: 6.5 },
      { name: "Barbell Box Steps with Curl and Press", met_value: 6.0 },
      { name: "Barbell Reverse Lunges with Russian Twists", met_value: 6.0 },
      { name: "Barbell Kneeling Crunches with Lat Pulldowns", met_value: 6.0 },
      { name: "Barbell Bench Press with Face Pulls", met_value: 6.0 },
      { name: "Barbell Squat Jumps with High Pulls", met_value: 7.0 },
      { name: "Barbell Farmer's Walk with Drag Curls", met_value: 7.0 },
      { name: "Barbell Leg Press with Glute Kickbacks", met_value: 6.0 },
      { name: "Barbell Skull Crushers with Upright Rows", met_value: 5.5 },
    ],
    kettlebell: [
      { name: "Kettlebell Swings with Goblet Squats", met_value: 6.5 },
      {
        name: "Kettlebell Turkish Get-ups with Russian Twists",
        met_value: 6.5,
      },
      { name: "Kettlebell Deadlifts with Rows", met_value: 5.5 },
      { name: "Kettlebell Cleans with High Pulls", met_value: 6.0 },
      { name: "Kettlebell Snatches with Lunges", met_value: 6.5 },
      {
        name: "Kettlebell Sumo Deadlift High Pulls with Glute Bridges",
        met_value: 6.0,
      },
      { name: "Kettlebell Windmills with Figure 8s", met_value: 5.0 },
      { name: "Kettlebell Farmer's Walk with Russian Press", met_value: 6.0 },
      {
        name: "Kettlebell Lateral Swings with Plank Pull-throughs",
        met_value: 5.5,
      },
      {
        name: "Kettlebell Bent-over Rows with Turkish Sit-ups",
        met_value: 5.5,
      },
      { name: "Kettlebell Side Bends with Goblet Lunges", met_value: 6.0 },
      {
        name: "Kettlebell Romanian Deadlifts with Split Squats",
        met_value: 6.0,
      },
      {
        name: "Kettlebell Cleans and Presses with Kettlebell Curls",
        met_value: 6.0,
      },
      {
        name: "Kettlebell Goblet Lunges with Kettlebell Swings",
        met_value: 6.5,
      },
      { name: "Kettlebell Sumo Squats with Side Swings", met_value: 6.5 },
      { name: "Kettlebell Figure 8 Lunges with High Pulls", met_value: 6.0 },
      { name: "Kettlebell Halo with Russian Twists", met_value: 6.0 },
      {
        name: "Kettlebell Turkish Sit-ups with Side Leg Raises",
        met_value: 6.0,
      },
      {
        name: "Kettlebell Single-leg Deadlifts with Single-arm Swings",
        met_value: 6.0,
      },
      {
        name: "Kettlebell Split Squats with Kettlebell Slingshots",
        met_value: 5.5,
      },
      {
        name: "Kettlebell Figure 8s with Kettlebell Upright Rows",
        met_value: 5.5,
      },
      {
        name: "Kettlebell Goblet Squats with Kettlebell Windmills",
        met_value: 6.0,
      },
      {
        name: "Kettlebell Russian Press with Kettlebell Goblet Swings",
        met_value: 6.5,
      },
      {
        name: "Kettlebell Turkish Get-ups with Kettlebell Cross Swings",
        met_value: 6.5,
      },
      {
        name: "Kettlebell Bulgarian Split Jumps with Kettlebell Lateral Swings",
        met_value: 7.0,
      },
    ],
    ball: [
      { name: "Stability Ball Squats with Wall Sits", met_value: 4.0 },
      { name: "Stability Ball Lunges with Push-ups", met_value: 4.5 },
      { name: "Stability Ball Plank with Russian Twists", met_value: 4.0 },
      { name: "Stability Ball Glute Bridges with Leg Curls", met_value: 4.0 },
      { name: "Stability Ball Wall Angels with Wall Sits", met_value: 3.5 },
      {
        name: "Stability Ball Rollouts with Stability Ball Side Leg Raises",
        met_value: 4.0,
      },
      { name: "Stability Ball Superman with Plank Rows", met_value: 4.0 },
      { name: "Stability Ball Tricep Dips with Bicep Curls", met_value: 4.0 },
      { name: "Stability Ball Hamstring Curls with Wall Sits", met_value: 4.5 },
      {
        name: "Stability Ball Pike with Stability Ball Leg Raises",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Mountain Climbers with Russian Twists",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Jackknives with Plank Rotations",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Chest Press with Stability Ball Lat Pulldowns",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Wall Sits with Stability Ball Arm Circles",
        met_value: 4.0,
      },
      {
        name: "Stability Ball Leg Circles with Stability Ball Side Leg Lifts",
        met_value: 4.0,
      },
      {
        name: "Stability Ball Push-ups with Stability Ball Front Raises",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Russian Twists with Stability Ball Bicycle Crunches",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Plank Pull-throughs with Stability Ball Pike",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Back Extensions with Stability Ball Wall Sits",
        met_value: 4.0,
      },
      {
        name: "Stability Ball Lateral Leg Raises with Stability Ball Leg Curls",
        met_value: 4.0,
      },
      {
        name: "Stability Ball Seated Crunches with Stability Ball Hip Raises",
        met_value: 4.0,
      },
      {
        name: "Stability Ball Wall Sits with Stability Ball Mountain Climbers",
        met_value: 5.0,
      },
      {
        name: "Stability Ball Superman with Stability Ball Russian Twists",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Plank Rows with Stability Ball Side Bends",
        met_value: 4.5,
      },
      {
        name: "Stability Ball Hamstring Curls with Stability Ball Rollouts",
        met_value: 4.5,
      },
    ],
    treadmill: [
      { name: "Treadmill Hill Climbs with Interval Walking", met_value: 6.5 },
      { name: "Treadmill Sprints with Incline Walking", met_value: 7.5 },
      { name: "Treadmill Side Shuffles with Brisk Walking", met_value: 6.0 },
      { name: "Treadmill Reverse Walking with Slow Jogging", met_value: 6.0 },
      {
        name: "Treadmill Stepper Climbs with Treadmill Lunges",
        met_value: 7.0,
      },
      {
        name: "Treadmill High Knees with Treadmill Butt Kicks",
        met_value: 7.5,
      },
      {
        name: "Treadmill Leg Swings with Treadmill Cross-Training",
        met_value: 6.5,
      },
      {
        name: "Treadmill Calf Raises with Treadmill Walking Deadlifts",
        met_value: 6.0,
      },
      {
        name: "Treadmill Arm Swings with Treadmill Side Leg Lifts",
        met_value: 6.0,
      },
      {
        name: "Treadmill Reverse Lunges with Treadmill Walking Lunges",
        met_value: 6.5,
      },
      { name: "Treadmill Push-ups with Treadmill Planks", met_value: 6.0 },
      {
        name: "Treadmill Mountain Climbers with Treadmill Side Steps",
        met_value: 7.0,
      },
      {
        name: "Treadmill Steady State Cardio with Treadmill Forward Pedaling",
        met_value: 6.0,
      },
      {
        name: "Treadmill Uphill Climbing with Treadmill Hill Intervals",
        met_value: 7.0,
      },
      {
        name: "Treadmill Cross Country Mode with Treadmill Glute Blaster",
        met_value: 7.0,
      },
      {
        name: "Treadmill Core Engage with Treadmill HIIT Workout",
        met_value: 7.5,
      },
      {
        name: "Treadmill Total Body Workout with Treadmill Cardio Workout",
        met_value: 7.0,
      },
      {
        name: "Treadmill Forward and Backward Motion with Treadmill Lateral Steps",
        met_value: 7.0,
      },
      {
        name: "Treadmill Arm Circles with Treadmill Leg Circles",
        met_value: 6.5,
      },
      {
        name: "Treadmill Side-to-Side Motion with Treadmill High Resistance",
        met_value: 7.5,
      },
      {
        name: "Treadmill Butt Kicks with Treadmill Single-Leg Pedaling",
        met_value: 7.0,
      },
      {
        name: "Treadmill Single-Arm Pedaling with Treadmill Side Bends",
        met_value: 6.5,
      },
    ],
    elliptical: [
      {
        name: "Elliptical Machine Cross Trainer with Forward Pedaling",
        met_value: 6.5,
      },
      {
        name: "Elliptical Machine High Resistance with Reverse Pedaling",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Cardio Workout with Interval Training",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Uphill Climbing with Cross Country Mode",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Glute Blaster with Core Engage",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine HIIT Workout with Total Body Workout",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Steady State Cardio with Forward and Backward Motion",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Lateral Steps with Arm Circles",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Leg Circles with Side-to-Side Motion",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine High Knee March with Butt Kicks",
        met_value: 8.0,
      },
      {
        name: "Elliptical Machine Single-Leg Pedaling with Single-Arm Pedaling",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Reverse Pedaling with Elliptical Machine Arm Focus",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Leg Focus with Elliptical Machine Forward and Backward Motion",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Cardio Workout with Uphill Climbing",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine High Resistance with Glute Blaster",
        met_value: 7.5,
      },
      { name: "Elliptical Machine Arm Focus with Leg Focus", met_value: 7.0 },
      {
        name: "Elliptical Machine Cross Trainer with High Resistance",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Total Body Workout with Cross Country Mode",
        met_value: 8.0,
      },
      {
        name: "Elliptical Machine Steady State Cardio with Elliptical Machine Cross Trainer",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Forward and Backward Motion with Elliptical Machine High Knee March",
        met_value: 8.0,
      },
      {
        name: "Elliptical Machine Butt Kicks with Single-Leg Pedaling",
        met_value: 7.5,
      },
      {
        name: "Elliptical Machine Single-Arm Pedaling with Elliptical Machine Cross Trainer",
        met_value: 7.0,
      },
      {
        name: "Elliptical Machine Cross Country Mode with Glute Blaster",
        met_value: 8.0,
      },
      {
        name: "Elliptical Machine Core Engage with High Resistance",
        met_value: 7.0,
      },
    ],
  },
  advance: {
    body_weight: [
      { name: "Handstand push-ups", met_value: 7.0 },
      { name: "One-arm push-ups", met_value: 8.0 },
      { name: "Pistol squats", met_value: 7.0 },
      { name: "Muscle-ups", met_value: 6.5 },
      { name: "Front lever holds", met_value: 6.0 },
      { name: "L-sit", met_value: 4.0 },
      { name: "Planche push-ups", met_value: 8.0 },
      { name: "Dragon flags", met_value: 7.0 },
      { name: "Archer push-ups", met_value: 7.0 },
      { name: "Plyometric push-ups", met_value: 6.5 },
      { name: "Clapping push-ups", met_value: 7.5 },
      { name: "Explosive box jumps", met_value: 8.5 },
      { name: "Hanging leg raises", met_value: 4.5 },
      { name: "Toes-to-bar", met_value: 5.0 },
      { name: "Human flag", met_value: 6.5 },
      { name: "HSPU (Handstand Push-Up) variations", met_value: 7.0 },
      { name: "Single-leg box jumps", met_value: 8.5 },
      { name: "One-arm pull-ups", met_value: 7.5 },
      { name: "One-arm push-up variations", met_value: 7.0 },
      { name: "Bulgarian bag swings", met_value: 6.0 },
      { name: "Parallette exercises (dips, push-ups, L-sits)", met_value: 5.0 },
      { name: "Turkish get-ups with a kettlebell", met_value: 5.5 },
      { name: "Kettlebell snatches", met_value: 6.0 },
      { name: "Kettlebell swings", met_value: 6.5 },
      { name: "Bar muscle-ups", met_value: 7.0 },
      { name: "Box handstand push-ups", met_value: 7.5 },
      { name: "Plyometric lunges", met_value: 8.0 },
      { name: "Depth jumps", met_value: 9.0 },
      {
        name: "Muscle-up variations (false grip, strict, kipping)",
        met_value: 7.0,
      },
      { name: "Explosive pistol squats", met_value: 8.0 },
      { name: "Renegade rows with dumbbells", met_value: 4.5 },
      { name: "Windmills with a kettlebell", met_value: 5.0 },
      { name: "Russian kettlebell swings", met_value: 6.5 },
      { name: "Kettlebell clean and press", met_value: 6.0 },
      { name: "Dragon flags with ankle weights", met_value: 7.5 },
      {
        name: "Isometric holds (planche, front lever, L-sit)",
        met_value: "Varies",
      },
      { name: "Clapping pull-ups", met_value: 7.5 },
      { name: "Bar dips with added weight", met_value: 6.5 },
      { name: "Archer pull-ups", met_value: 7.0 },
      { name: "Hollow body holds", met_value: 4.0 },
      { name: "Hanging windshield wipers", met_value: 5.0 },
      { name: "Ring dips", met_value: 6.0 },
      { name: "Box jump burpees", met_value: 8.5 },
      { name: "Plyometric box push-ups", met_value: 7.0 },
      { name: "Advanced tuck planche", met_value: 7.0 },
      { name: "Triple clap push-ups", met_value: 8.0 },
      { name: "Iron cross (ring exercise)", met_value: 8.0 },
      { name: "Muscle-up to handstand", met_value: 7.5 },
      { name: "Planche to push-up", met_value: 8.0 },
      { name: "Kettlebell Turkish get-ups with added weight", met_value: 6.0 },
    ],
    dumbbell: [
      { name: "Dumbbell Snatches with Overhead Squats", met_value: 7.5 },
      { name: "Dumbbell Clean and Jerks", met_value: 7.0 },
      { name: "Dumbbell Thrusters with Burpees", met_value: 8.0 },
      { name: "Dumbbell Man Makers", met_value: 8.5 },
      { name: "Dumbbell Turkish Get-ups with Windmills", met_value: 7.5 },
      { name: "Dumbbell Push Press with Renegade Rows", met_value: 7.0 },
      { name: "Dumbbell Pistol Squats", met_value: 8.0 },
      { name: "Dumbbell Lateral Raise Drop Sets", met_value: 7.0 },
      { name: "Dumbbell Pull-Overs", met_value: 6.5 },
      { name: "Dumbbell Bench Press with Flyes", met_value: 7.0 },
      { name: "Dumbbell Inverted Rows", met_value: 6.5 },
      { name: "Dumbbell Box Jumps with Weighted Vest", met_value: 9.0 },
      { name: "Dumbbell Farmer's Walk with Farmer's Walk", met_value: 8.5 },
      {
        name: "Dumbbell Russian Twists with Medicine Ball Slams",
        met_value: 7.5,
      },
      { name: "Dumbbell Plank Rows with Plank Hold", met_value: 7.0 },
      { name: "Dumbbell Squat Jumps with Tuck Jumps", met_value: 9.0 },
      { name: "Dumbbell Sled Push with Sled Pull", met_value: 9.0 },
      { name: "Dumbbell Battle Ropes with Battle Ropes", met_value: 9.0 },
      { name: "Dumbbell Wall Balls with Wall Balls", met_value: 8.0 },
      { name: "Dumbbell Tire Flips with Tire Flips", met_value: 9.0 },
      { name: "Dumbbell Rope Climbs with Rope Climbs", met_value: 9.0 },
      {
        name: "Dumbbell Sledgehammer Swings with Sledgehammer Swings",
        met_value: 9.0,
      },
      {
        name: "Dumbbell Kettlebell Swings with Kettlebell Swings",
        met_value: 8.0,
      },
      {
        name: "Dumbbell Barbell Complexes with Barbell Complexes",
        met_value: 8.5,
      },
      {
        name: "Dumbbell TRX Suspension Training with TRX Suspension Training",
        met_value: 8.0,
      },
      {
        name: "Dumbbell Plyometric Box Jumps with Plyometric Box Jumps",
        met_value: 9.0,
      },
    ],
    band: [
      { name: "Resistance Band Plyometric Push-ups", met_value: 7.5 },
      { name: "Resistance Band Plyometric Lunges", met_value: 8.0 },
      { name: "Resistance Band Explosive Rows", met_value: 7.0 },
      { name: "Resistance Band Power Snatches", met_value: 8.0 },
      { name: "Resistance Band Burpee Broad Jumps", met_value: 8.5 },
      { name: "Resistance Band Lateral Plyometric Steps", met_value: 7.0 },
      { name: "Resistance Band Explosive Bicep Curls", met_value: 7.0 },
      { name: "Resistance Band Tuck Jumps", met_value: 8.5 },
      { name: "Resistance Band Kettlebell Swings", met_value: 8.0 },
      { name: "Resistance Band Barbell Complexes", met_value: 8.5 },
      { name: "Resistance Band TRX Suspension Training", met_value: 8.0 },
      { name: "Resistance Band Plyometric Box Jumps", met_value: 9.0 },
      { name: "Resistance Band Medicine Ball Slams", met_value: 7.5 },
      { name: "Resistance Band Plank Rows with Plank Hold", met_value: 7.0 },
      { name: "Resistance Band Sled Push with Sled Pull", met_value: 9.0 },
      {
        name: "Resistance Band Battle Ropes with Battle Ropes",
        met_value: 9.0,
      },
      { name: "Resistance Band Wall Balls with Wall Balls", met_value: 8.0 },
      { name: "Resistance Band Tire Flips with Tire Flips", met_value: 9.0 },
      { name: "Resistance Band Rope Climbs with Rope Climbs", met_value: 9.0 },
      {
        name: "Resistance Band Sledgehammer Swings with Sledgehammer Swings",
        met_value: 9.0,
      },
      {
        name: "Resistance Band Dumbbell Swings with Dumbbell Swings",
        met_value: 8.0,
      },
      {
        name: "Resistance Band Barbell Complexes with Barbell Complexes",
        met_value: 8.5,
      },
      {
        name: "Resistance Band TRX Suspension Training with TRX Suspension Training",
        met_value: 8.0,
      },
      {
        name: "Resistance Band Plyometric Box Jumps with Plyometric Box Jumps",
        met_value: 9.0,
      },
      {
        name: "Resistance Band Kettlebell Swings with Kettlebell Swings",
        met_value: 8.0,
      },
    ],
    barbell: [
      { name: "Barbell Clean and Jerks with Front Squats", met_value: 8.0 },
      { name: "Barbell Thrusters with Burpees", met_value: 8.5 },
      { name: "Barbell Man Makers with Dumbbell Snatches", met_value: 8.5 },
      { name: "Barbell Turkish Get-ups with Windmills", met_value: 8.0 },
      {
        name: "Barbell Snatch Grip Deadlifts with Bent-Over Rows",
        met_value: 7.5,
      },
      { name: "Barbell Deadlifts with Hang Cleans", met_value: 8.0 },
      { name: "Barbell Push Press with Renegade Rows", met_value: 7.5 },
      { name: "Barbell Pistol Squats with Weighted Vest", met_value: 9.0 },
      {
        name: "Barbell Lateral Raise Drop Sets with Medicine Ball Slams",
        met_value: 8.0,
      },
      { name: "Barbell Pull-Overs with Plank Rows", met_value: 7.0 },
      { name: "Barbell Bench Press with Flyes", met_value: 7.5 },
      { name: "Barbell Inverted Rows with Barbell Rows", met_value: 7.0 },
      { name: "Barbell Box Jumps with Barbell Lunges", met_value: 8.5 },
      { name: "Barbell Farmer's Walk with Farmer's Walk", met_value: 9.0 },
      { name: "Barbell Russian Twists with Sled Push", met_value: 8.5 },
      { name: "Barbell Plank Rows with Plank Hold", met_value: 7.5 },
      { name: "Barbell Squat Jumps with Tuck Jumps", met_value: 9.0 },
      { name: "Barbell Sled Push with Battle Ropes", met_value: 9.0 },
      { name: "Barbell Battle Ropes with Wall Balls", met_value: 8.5 },
      { name: "Barbell Wall Balls with Tire Flips", met_value: 9.0 },
      { name: "Barbell Tire Flips with Rope Climbs", met_value: 9.0 },
      { name: "Barbell Rope Climbs with Sledgehammer Swings", met_value: 9.0 },
      {
        name: "Barbell Kettlebell Swings with Dumbbell Swings",
        met_value: 8.0,
      },
      {
        name: "Barbell TRX Suspension Training with Plyometric Box Jumps",
        met_value: 9.0,
      },
      {
        name: "Barbell Plyometric Box Jumps with Medicine Ball Slams",
        met_value: 8.5,
      },
    ],
    kettlebell: [
      {
        name: "Kettlebell Snatch Grip Deadlifts with Front Squats",
        met_value: 8.0,
      },
      {
        name: "Kettlebell Clean and Jerks with Turkish Get-ups",
        met_value: 8.5,
      },
      { name: "Kettlebell Thrusters with Burpee Broad Jumps", met_value: 9.0 },
      { name: "Kettlebell Man Makers with Windmills", met_value: 8.5 },
      { name: "Kettlebell Explosive Rows with Power Snatches", met_value: 8.0 },
      { name: "Kettlebell Deadlifts with Kettlebell Swings", met_value: 8.0 },
      {
        name: "Kettlebell Push Press with Kettlebell Turkish Get-ups",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Pistol Squats with Kettlebell Windmills",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Lateral Raise Drop Sets with Kettlebell Pull-Overs",
        met_value: 8.0,
      },
      {
        name: "Kettlebell Bench Press with Kettlebell Inverted Rows",
        met_value: 7.5,
      },
      {
        name: "Kettlebell Box Jumps with Kettlebell Farmer's Walk",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Russian Twists with Kettlebell Plank Rows",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Squat Jumps with Kettlebell Sled Push",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Battle Ropes with Kettlebell Wall Balls",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Wall Balls with Kettlebell Tire Flips",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Tire Flips with Kettlebell Rope Climbs",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Rope Climbs with Kettlebell Sledgehammer Swings",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Dumbbell Swings with Kettlebell Barbell Complexes",
        met_value: 8.5,
      },
      {
        name: "Kettlebell TRX Suspension Training with Kettlebell Plyometric Box Jumps",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Plyometric Box Jumps with Kettlebell Medicine Ball Slams",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Plank Rows with Kettlebell Squat Jumps",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Sled Push with Kettlebell Battle Ropes",
        met_value: 9.0,
      },
      {
        name: "Kettlebell Medicine Ball Slams with Kettlebell Plank Rows",
        met_value: 8.5,
      },
      {
        name: "Kettlebell Glute Bridges with Kettlebell Leg Curls",
        met_value: 7.0,
      },
      {
        name: "Kettlebell Wall Angels with Kettlebell Rollouts",
        met_value: 7.0,
      },
    ],
    ball: [
      {
        name: "Stability Ball Plyometric Squats with Wall Sits",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Lunges with Push-ups",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Plank with Medicine Ball Slams",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Glute Bridges with Leg Curls",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Wall Angels with Wall Sits",
        met_value: 6.5,
      },
      {
        name: "Stability Ball Plyometric Rollouts with Stability Ball Side Leg Raises",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Superman with Plank Rows",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Tricep Dips with Bicep Curls",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Hamstring Curls with Wall Sits",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Pike with Stability Ball Leg Raises",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Mountain Climbers with Medicine Ball Slams",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Jackknives with Plank Rotations",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Chest Press with Stability Ball Lat Pulldowns",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Wall Sits with Stability Ball Arm Circles",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Leg Circles with Stability Ball Side Leg Lifts",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Push-ups with Stability Ball Front Raises",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Russian Twists with Stability Ball Bicycle Crunches",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Plank Pull-throughs with Stability Ball Pike",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Back Extensions with Stability Ball Wall Sits",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Lateral Leg Raises with Stability Ball Leg Curls",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Seated Crunches with Stability Ball Hip Raises",
        met_value: 7.0,
      },
      {
        name: "Stability Ball Plyometric Wall Sits with Stability Ball Mountain Climbers",
        met_value: 8.0,
      },
      {
        name: "Stability Ball Plyometric Superman with Stability Ball Russian Twists",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Plank Rows with Stability Ball Side Bends",
        met_value: 7.5,
      },
      {
        name: "Stability Ball Plyometric Hamstring Curls with Stability Ball Rollouts",
        met_value: 7.5,
      },
    ],
    treadmill: [
      {
        name: "Treadmill Plyometric Hill Climbs with Interval Walking",
        met_value: 8.5,
      },
      {
        name: "Treadmill Plyometric Sprints with Incline Walking",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Side Shuffles with Brisk Walking",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Reverse Walking with Slow Jogging",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Stepper Climbs with Treadmill Lunges",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric High Knees with Treadmill Butt Kicks",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Leg Swings with Treadmill Cross-Training",
        met_value: 8.5,
      },
      {
        name: "Treadmill Plyometric Calf Raises with Treadmill Walking Deadlifts",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Arm Swings with Treadmill Side Leg Lifts",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Reverse Lunges with Treadmill Walking Lunges",
        met_value: 8.5,
      },
      {
        name: "Treadmill Plyometric Push-ups with Treadmill Planks",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Mountain Climbers with Treadmill Side Steps",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Steady State Cardio with Treadmill Forward Pedaling",
        met_value: 8.0,
      },
      {
        name: "Treadmill Plyometric Uphill Climbing with Treadmill Hill Intervals",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Cross Country Mode with Treadmill Glute Blaster",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Core Engage with Treadmill HIIT Workout",
        met_value: 9.5,
      },
      {
        name: "Treadmill Plyometric Total Body Workout with Treadmill Cardio Workout",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Forward and Backward Motion with Treadmill Lateral Steps",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Arm Circles with Treadmill Leg Circles",
        met_value: 8.5,
      },
      {
        name: "Treadmill Plyometric Side-to-Side Motion with Treadmill High Resistance",
        met_value: 9.5,
      },
      {
        name: "Treadmill Plyometric Butt Kicks with Treadmill Single-Leg Pedaling",
        met_value: 9.0,
      },
      {
        name: "Treadmill Plyometric Single-Arm Pedaling with Treadmill Side Bends",
        met_value: 8.5,
      },
      {
        name: "Treadmill Plyometric Hill Sprints with Treadmill Mountain Climbers",
        met_value: 9.5,
      },
    ],
    elliptical: [
      {
        name: "Elliptical Plyometric Cross Trainer with Forward Pedaling",
        met_value: 8.5,
      },
      {
        name: "Elliptical Plyometric High Resistance with Reverse Pedaling",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Cardio Workout with Interval Training",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Uphill Climbing with Cross Country Mode",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Glute Blaster with Core Engage",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric HIIT Workout with Total Body Workout",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Steady State Cardio with Forward and Backward Motion",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Lateral Steps with Arm Circles",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Leg Circles with Side-to-Side Motion",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric High Knee March with Butt Kicks",
        met_value: 10.0,
      },
      {
        name: "Elliptical Plyometric Single-Leg Pedaling with Single-Arm Pedaling",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Reverse Pedaling with Elliptical Plyometric Arm Focus",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Leg Focus with Elliptical Plyometric Forward and Backward Motion",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Cardio Workout with Uphill Climbing",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric High Resistance with Glute Blaster",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Arm Focus with Leg Focus",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Cross Trainer with High Resistance",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Total Body Workout with Cross Country Mode",
        met_value: 10.0,
      },
      {
        name: "Elliptical Plyometric Steady State Cardio with Elliptical Plyometric Cross Trainer",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Forward and Backward Motion with Elliptical Plyometric High Knee March",
        met_value: 10.0,
      },
      {
        name: "Elliptical Plyometric Butt Kicks with Single-Leg Pedaling",
        met_value: 9.5,
      },
      {
        name: "Elliptical Plyometric Single-Arm Pedaling with Elliptical Plyometric Cross Trainer",
        met_value: 9.0,
      },
      {
        name: "Elliptical Plyometric Cross Country Mode with Glute Blaster",
        met_value: 10.0,
      },
      {
        name: "Elliptical Plyometric Core Engage with High Resistance",
        met_value: 9.0,
      },
    ],
  },
};
